import type { ReactNode } from "react";
import { ArrowRight, Check, CheckCheck, Code2, FileText, Globe, Headphones, Lock, MessageCircle, Network, Phone, PhoneCall, Send, Server, ShieldCheck, Smartphone, Users, Webhook } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ProductSceneStage, SceneCallControls, SceneLaptop, ScenePerson, ScenePhone, ScenePosition, SceneRow, SceneStatus, SceneTile, SceneWave, SceneWindow } from "@/components/site/product-scene-primitives";

// Each scene is a different illustrative workflow, not a claim of a live UI.
function CodeLines({ lines }: { lines: string[] }) {
  return <div className="space-y-[0.8cqw] p-[2cqw] font-mono text-[1.1cqw] leading-relaxed">{lines.map((line, i) => <div key={i} className="flex gap-[1.4cqw]"><span className="w-[1.2cqw] shrink-0 text-background/30">{i + 1}</span><span className={line.startsWith("//") ? "text-background/45" : "text-background/90"}>{line || "\u00a0"}</span></div>)}</div>;
}

function Bubble({ children, outgoing = false }: { children: ReactNode; outgoing?: boolean }) {
  return <div className={`max-w-[90%] rounded-[1.1cqw] p-[1.1cqw] text-[1.1cqw] ${outgoing ? "ml-auto rounded-br-none bg-accent text-accent-foreground" : "rounded-bl-none bg-muted text-foreground"}`}>{children}</div>;
}

function DialPad() {
  return <div className="grid grid-cols-3 gap-[0.6cqw]">{["1", "2 ABC", "3 DEF", "4 GHI", "5 JKL", "6 MNO", "7 PQRS", "8 TUV", "9 WXYZ", "*", "0 +", "#"].map(value => <span key={value} className="flex h-[3.2cqw] items-center justify-center rounded-[0.6cqw] bg-muted text-[1.1cqw] font-medium">{value}</span>)}</div>;
}

function VoiceApiScene() {
  return <ProductSceneStage name="voice-api" label="Illustration of application call code connected to a customer phone and returning webhook events" wires={[{ from: "voice-product", to: "voice-application", lit: true }, { from: "voice-call", to: "voice-customer", lit: true }, { from: "voice-customer-events", to: "voice-events", lit: true }, { from: "voice-event-return", to: "voice-webhook", lit: true }]}>
    <ScenePosition x={65} y={70} w={520} joints={[{ id: "voice-application", side: "b", left: "25%", top: "100%" }, { id: "voice-call", side: "r", left: "100%", top: "42%" }, { id: "voice-webhook", side: "b", left: "80%", top: "100%" }]}><SceneWindow title="Your application / call workflow" dark><div className="flex border-b border-background/15 px-[2cqw] py-[0.8cqw] text-[1cqw]"><span className="text-background/60">call.ts</span><span className="ml-auto text-background/40">Illustrative code</span></div><CodeLines lines={["// Connect a customer to your team", "const call = await voice.call({", "  customer: contact.phone,", "  destination: support.agent,", "  events: ['answered', 'ended']", "});", "", "await crm.logCall(call);"]} /></SceneWindow></ScenePosition>
    <ScenePosition x={745} y={35} w={210} joints={[{ id: "voice-customer", side: "l", left: "0%", top: "24%" }, { id: "voice-customer-events", side: "b", left: "50%", top: "100%" }]}><ScenePhone title="Incoming business call"><div className="space-y-[2cqw] px-[1.5cqw] py-[3cqw]"><ScenePerson name="Your customer" detail="From your application" /><SceneWave animated /><SceneCallControls /><p className="text-center text-[0.95cqw] text-muted-foreground">Voice, inside your workflow</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={355} y={450} w={365} joints={[{ id: "voice-events", side: "r", left: "100%", top: "55%" }, { id: "voice-event-return", side: "t", left: "35%", top: "0%" }]}><SceneWindow title="Event stream"><SceneRow><Webhook className="size-[1.5cqw] text-primary" /><span className="flex-1 font-mono text-[1cqw]">call.created</span><SceneStatus>Received</SceneStatus></SceneRow><SceneRow><Webhook className="size-[1.5cqw] text-primary" /><span className="flex-1 font-mono text-[1cqw]">call.answered</span><SceneStatus>Received</SceneStatus></SceneRow><SceneRow><FileText className="size-[1.5cqw] text-primary" /><span className="flex-1">CRM activity updated</span><Check className="size-[1.3cqw] text-primary" /></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={65} y={455} w={230} joints={[{ id: "voice-product", side: "t", left: "55%", top: "0%" }]}><SceneTile icon={Code2} title="Your product" detail="Own the calling experience" /></ScenePosition>
  </ProductSceneStage>;
}

function SmsApiScene() {
  return <ProductSceneStage name="sms-api" label="Illustration of SMS composition, a customer notification and delivery event tracking" wires={[{ from: "sms-send", to: "sms-customer", lit: true }, { from: "sms-application", to: "sms-journey-start", lit: true }, { from: "sms-delivery", to: "sms-journey-end", lit: true }]}>
    <ScenePosition x={45} y={60} w={550} joints={[{ id: "sms-send", side: "r", left: "100%", top: "58%" }, { id: "sms-application", side: "b", left: "22%", top: "100%" }]}><SceneWindow title="SMS workspace / compose"><div className="grid grid-cols-[1fr_3fr]"><div className="space-y-[1.6cqw] border-r border-border bg-muted/30 p-[1.5cqw]"><p className="font-semibold text-primary">Messages</p><p className="text-muted-foreground">Templates</p><p className="text-muted-foreground">Delivery</p><p className="text-muted-foreground">Webhooks</p></div><div className="space-y-[1.5cqw] p-[2cqw]"><div><p className="text-[0.9cqw] text-muted-foreground">Recipient</p><div className="mt-[0.5cqw] rounded-[0.7cqw] border border-border p-[1cqw]">Customer mobile number</div></div><div><p className="text-[0.9cqw] text-muted-foreground">Message</p><div className="mt-[0.5cqw] rounded-[0.7cqw] border border-border p-[1cqw]">Your appointment is confirmed.<br />Reply if you need to change it.</div></div><div className="flex items-center justify-between"><Badge size="scene" variant="secondary" className="text-[0.85cqw]">Transactional SMS</Badge><span className="flex items-center gap-[0.5cqw] rounded-[0.6cqw] bg-primary px-[1cqw] py-[0.6cqw] text-[1cqw] text-primary-foreground"><Send className="size-[1.1cqw]" />Send message</span></div></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={745} y={40} w={220} joints={[{ id: "sms-customer", side: "l", left: "0%", top: "30%" }, { id: "sms-delivery", side: "b", left: "50%", top: "100%" }]}><ScenePhone title="Messages"><div className="min-h-[23cqw] space-y-[1.2cqw] bg-muted/30 p-[1.6cqw]"><p className="text-center text-[0.9cqw] text-muted-foreground">Today</p><Bubble>Your appointment is confirmed. Reply if you need to change it.</Bubble><Bubble outgoing>Thank you. See you then!</Bubble><p className="text-right text-[0.85cqw] text-muted-foreground">Customer conversation</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={45} y={430} w={620} joints={[{ id: "sms-journey-start", side: "t", left: "20%", top: "0%" }, { id: "sms-journey-end", side: "r", left: "100%", top: "55%" }]}><SceneWindow title="Message journey"><div className="flex items-center justify-between p-[2cqw]">{["Application", "SMS request", "Customer phone", "Delivery event"].map((value, i) => <div key={value} className="flex items-center gap-[1.2cqw]"><div className="text-center"><span className="mx-auto flex size-[2.8cqw] items-center justify-center rounded-full bg-accent text-primary"><Check className="size-[1.4cqw]" /></span><p className="mt-[0.5cqw] text-[1cqw]">{value}</p></div>{i < 3 && <ArrowRight className="size-[1.6cqw] text-primary/50" />}</div>)}</div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function WhatsappScene() {
  return <ProductSceneStage name="whatsapp-api" label="Illustration of a WhatsApp customer conversation, business inbox and approved message templates" wires={[{ from: "whatsapp-customer", to: "whatsapp-inbox", lit: true }, { from: "whatsapp-template-send", to: "whatsapp-template-message", lit: true }, { from: "whatsapp-inbox-templates", to: "whatsapp-templates", lit: true }]}>
    <ScenePosition x={55} y={35} w={245} joints={[{ id: "whatsapp-customer", side: "r", left: "100%", top: "33%" }, { id: "whatsapp-template-message", side: "r", left: "100%", top: "74%" }]}><ScenePhone title="SipLink business"><div className="space-y-[1.2cqw] bg-accent/30 px-[1.4cqw] py-[2cqw]"><p className="text-center text-[0.85cqw] text-muted-foreground">Business conversation</p><Bubble>Hello! I have a question about my order.</Bubble><Bubble outgoing>Hi Sarah, happy to help. Which order is it?</Bubble><Bubble>My recent office delivery.</Bubble><Bubble outgoing>I have the details. Let me check for you.<CheckCheck className="ml-auto mt-[0.4cqw] size-[1.2cqw] text-primary" /></Bubble><div className="flex items-center gap-[0.8cqw] rounded-full bg-card px-[1cqw] py-[0.8cqw]"><span className="flex-1 text-muted-foreground">Message</span><Send className="size-[1.3cqw] text-primary" /></div></div></ScenePhone></ScenePosition>
    <ScenePosition x={415} y={65} w={535} joints={[{ id: "whatsapp-inbox", side: "l", left: "0%", top: "27%" }, { id: "whatsapp-inbox-templates", side: "b", left: "65%", top: "100%" }]}><SceneWindow title="Business conversation inbox"><div className="grid grid-cols-[1fr_1.7fr]"><div className="border-r border-border"><SceneRow active><span>Sarah Johnson<br /><small className="text-muted-foreground">Order question</small></span><Badge size="scene" className="px-[0.5cqw] text-[0.8cqw]">New</Badge></SceneRow><SceneRow><span>Office supplies<br /><small className="text-muted-foreground">Delivery update</small></span></SceneRow><SceneRow><span>Support team<br /><small className="text-muted-foreground">Assigned conversations</small></span></SceneRow></div><div className="space-y-[1.5cqw] p-[1.7cqw]"><ScenePerson compact detail="Customer context" /><div className="rounded-[0.8cqw] bg-muted p-[1.2cqw]"><p className="font-medium">Order question</p><p className="mt-[0.5cqw] text-muted-foreground">A conversation your team can pick up and continue.</p></div><SceneStatus>Assigned to support</SceneStatus></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={430} y={415} w={490} joints={[{ id: "whatsapp-template-send", side: "l", left: "0%", top: "60%" }, { id: "whatsapp-templates", side: "t", left: "68%", top: "0%" }]}><SceneWindow title="Message templates"><div className="grid grid-cols-2 gap-[1cqw] p-[1.5cqw]">{["Order update", "Appointment reminder"].map(value => <div key={value} className="rounded-[1cqw] border border-border p-[1cqw]"><MessageCircle className="mb-[0.8cqw] size-[2cqw] text-primary" /><p className="font-semibold">{value}</p><p className="mt-[0.6cqw] text-[0.9cqw] text-muted-foreground">Reusable business message</p></div>)}</div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function WebrtcScene() {
return <ProductSceneStage name="webrtc-sdk" label="Illustration of browser calling connected to a laptop application and mobile device" wires={[{ from: "rtc-web", to: "rtc-application-web", lit: true }, { from: "rtc-browser", to: "rtc-application-browser", lit: true }, { from: "rtc-application-sdk", to: "rtc-sdk", lit: true }, { from: "rtc-sdk-mobile", to: "rtc-phone-sdk", lit: true }, { from: "rtc-mobile", to: "rtc-phone-mobile", lit: true }]}>
    <ScenePosition x={285} y={45} w={490} joints={[{ id: "rtc-application-web", side: "l", left: "0%", top: "25%" }, { id: "rtc-application-browser", side: "l", left: "0%", top: "75%" }, { id: "rtc-application-sdk", side: "b", left: "58%", top: "100%" }]}><SceneLaptop title="Calling inside your application"><div className="grid grid-cols-[1fr_3fr_1.4fr]"><div className="space-y-[1.2cqw] border-r border-border p-[1.1cqw] text-[0.9cqw]"><p>Home</p><p className="rounded-[0.5cqw] bg-accent p-[0.5cqw] text-primary">Calls</p><p>Team</p><p>History</p></div><div className="space-y-[1.5cqw] bg-accent/25 p-[2.5cqw]"><div className="text-center"><SceneStatus>Browser audio</SceneStatus></div><ScenePerson detail="Customer conversation" /><SceneWave animated /><SceneCallControls /></div><div className="space-y-[1cqw] border-l border-border p-[1cqw]"><p className="font-semibold">Team</p>{["Daniel Ortiz", "Marcus Lee", "Elena Ruiz", "Chris Moore"].map(value => <div key={value} className="flex items-center gap-[0.5cqw]"><span className="size-[1.5cqw] rounded-full bg-primary/15" /><span className="text-[0.75cqw]">{value}<small className="block text-muted-foreground">Available</small></span></div>)}</div></div></SceneLaptop></ScenePosition>
    <ScenePosition x={25} y={235} w={230} joints={[{ id: "rtc-browser", side: "r", left: "100%", top: "40%" }]}><SceneWindow title="Your website / call"><div className="space-y-[1.5cqw] p-[2cqw]"><ScenePerson detail="Calling from the browser" /><SceneCallControls /><p className="border-t border-border pt-[1cqw] text-center text-[0.9cqw] text-muted-foreground">WebRTC · no separate application</p></div></SceneWindow></ScenePosition>
    <ScenePosition x={815} y={210} w={165} joints={[{ id: "rtc-phone-sdk", side: "l", left: "0%", top: "78%" }, { id: "rtc-phone-mobile", side: "t", left: "50%", top: "0%" }]}><ScenePhone title="Application voice"><div className="space-y-[1.4cqw] px-[1cqw] py-[2.7cqw]"><ScenePerson detail="On mobile" /><SceneWave animated /><SceneCallControls /></div></ScenePhone></ScenePosition>
    <ScenePosition x={45} y={65} w={150} joints={[{ id: "rtc-web", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Globe} title="Web" /></ScenePosition>
    <ScenePosition x={820} y={65} w={150} joints={[{ id: "rtc-mobile", side: "b", left: "50%", top: "100%" }]}><SceneTile icon={Smartphone} title="Mobile" /></ScenePosition>
    <ScenePosition x={440} y={485} w={270} joints={[{ id: "rtc-sdk", side: "t", left: "48%", top: "0%" }, { id: "rtc-sdk-mobile", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Code2} title="WebRTC SDK" detail="Embedded voice" /></ScenePosition>
  </ProductSceneStage>;
}

function SipApiScene() {
return <ProductSceneStage name="sip-api" label="Illustration of SIP configuration code, a signalling ladder and registered PBX endpoints" wires={[{ from: "sip-configuration", to: "sip-session", lit: true }, { from: "sip-session-pbx", to: "sip-office-pbx", lit: true }, { from: "sip-session-endpoints", to: "sip-endpoints", lit: true }, { from: "sip-config-routing", to: "sip-routing", lit: true }]}>
    <ScenePosition x={35} y={90} w={330} joints={[{ id: "sip-configuration", side: "r", left: "100%", top: "33%" }, { id: "sip-config-routing", side: "b", left: "65%", top: "100%" }]}><SceneWindow title="SIP configuration" dark><CodeLines lines={["// Your voice architecture", "trunk.configure({", "  route: 'business',", "  endpoint: 'office-pbx',", "  registration: true", "});", "", "session.on('invite',", "  handleInboundCall", ");"]} /></SceneWindow></ScenePosition>
    <ScenePosition x={415} y={65} w={330} joints={[{ id: "sip-session", side: "l", left: "0%", top: "35%" }, { id: "sip-session-pbx", side: "r", left: "100%", top: "30%" }, { id: "sip-session-endpoints", side: "r", left: "100%", top: "78%" }]}><SceneWindow title="Session signalling"><div className="relative p-[2cqw]"><div className="flex justify-between font-semibold"><span>Application</span><span>SIP network</span></div><div className="mt-[2cqw] space-y-[1.7cqw] border-x border-dashed border-primary/35 px-[1cqw] pb-[2cqw]">{["INVITE →", "← Ringing", "← Answer", "ACK →", "← Media →", "BYE →"].map((value, i) => <div key={value} className={`border-b border-primary/25 pb-[0.5cqw] text-[1cqw] ${i === 4 ? "rounded-full border-0 bg-accent py-[1cqw] text-center text-primary" : i === 1 || i === 2 ? "text-left" : "text-right"}`}>{value}</div>)}</div></div></SceneWindow></ScenePosition>
    <ScenePosition x={815} y={45} w={170} joints={[{ id: "sip-office-pbx", side: "l", left: "0%", top: "55%" }]}><SceneTile icon={Server} title="Office PBX" detail="Existing SIP system" /></ScenePosition>
    <ScenePosition x={815} y={450} w={180} joints={[{ id: "sip-endpoints", side: "l", left: "0%", top: "45%" }]}><SceneTile icon={Phone} title="IP endpoints" detail="Phones and softphones" /></ScenePosition>
    <ScenePosition x={400} y={485} w={370} joints={[{ id: "sip-routing", side: "l", left: "0%", top: "35%" }]}><SceneWindow title="Routing rules"><SceneRow><span>Business destination</span><Badge size="scene" variant="secondary" className="text-[0.85cqw]">Office trunk</Badge></SceneRow><SceneRow><span>Application workflow</span><ArrowRight className="size-[1.5cqw] text-primary" /></SceneRow></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function TeamsScene() {
return <ProductSceneStage name="teams-calling" label="Illustration of a Teams-style collaboration workspace, external calling dial pad and desk phone" wires={[{ from: "teams-dial-out", to: "teams-dial-pad", lit: true }, { from: "teams-workspace-route", to: "teams-routing", lit: true }, { from: "teams-routing-phone", to: "teams-reception", lit: true }]}>
    <ScenePosition x={85} y={40} w={615} joints={[{ id: "teams-dial-out", side: "r", left: "100%", top: "40%" }, { id: "teams-workspace-route", side: "b", left: "22%", top: "100%" }]}><SceneLaptop detailed title="Team collaboration + business calls"><div className="grid grid-cols-[1fr_3.3fr]"><div className="space-y-[1.3cqw] border-r border-border bg-muted/50 p-[1.3cqw] text-[1cqw]"><Users className="size-[2cqw] text-primary" /><p>Activity</p><p>Chat</p><p>Calendar</p><p className="rounded-[0.5cqw] bg-accent p-[0.5cqw] font-semibold text-primary">Calls</p></div><div className="p-[2cqw]"><div className="flex items-center justify-between"><p className="text-[1.8cqw] font-semibold">Your working day</p><SceneStatus>Business voice</SceneStatus></div><div className="mt-[2cqw] grid grid-cols-2 gap-[1.5cqw]"><div className="space-y-[1.3cqw]"><p className="font-semibold">People</p>{["Customer support", "Sales team", "Reception"].map(value => <div key={value} className="flex items-center gap-[1cqw]"><span className="flex size-[2.6cqw] items-center justify-center rounded-full bg-accent text-primary"><Users className="size-[1.3cqw]" /></span><span>{value}<small className="block text-[0.9cqw] text-muted-foreground">Business number mapped</small></span></div>)}</div><div className="rounded-[1cqw] bg-accent/40 p-[1.5cqw]"><p className="font-semibold">External calls</p><p className="mt-[1cqw] text-muted-foreground">Customers, suppliers and partners.</p><div className="mt-[1.5cqw] flex items-center gap-[0.8cqw] text-primary"><PhoneCall className="size-[1.7cqw]" /><span>Call from your workspace</span></div></div></div></div></div></SceneLaptop></ScenePosition>
    <ScenePosition x={745} y={45} w={220} joints={[{ id: "teams-dial-pad", side: "l", left: "0%", top: "52%" }]}><SceneWindow title="Dial a number"><div className="space-y-[1.2cqw] p-[1.5cqw]"><div className="rounded-[0.6cqw] border border-border p-[0.9cqw] text-center">Business destination</div><DialPad /><span className="mx-auto flex size-[3.5cqw] items-center justify-center rounded-full bg-primary text-primary-foreground"><Phone className="size-[1.6cqw]" /></span></div></SceneWindow></ScenePosition>
    <ScenePosition x={635} y={485} w={320} joints={[{ id: "teams-reception", side: "l", left: "0%", top: "50%" }]}><Card className="gap-0 rounded-[2cqw] bg-foreground p-[1.5cqw] text-background shadow-xl shadow-primary/15"><CardContent className="flex gap-[1.8cqw] p-0"><div className="flex w-[4cqw] items-center justify-center rounded-[1.5cqw] bg-background/10"><Phone className="size-[3cqw]" /></div><div className="flex-1"><div className="rounded-[0.6cqw] bg-accent p-[1cqw] text-accent-foreground"><p className="font-semibold">Reception</p><p className="text-[0.85cqw]">Business voice endpoint</p></div><div className="mt-[1cqw] grid grid-cols-3 gap-[0.5cqw]">{Array.from({length:6},(_,i)=><span key={i} className="h-[1cqw] rounded-sm bg-background/20" />)}</div></div></CardContent></Card></ScenePosition>
    <ScenePosition x={35} y={500} w={420} joints={[{ id: "teams-routing", side: "t", left: "52%", top: "0%" }, { id: "teams-routing-phone", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Network} title="Direct Routing" detail="Your collaboration workspace meets the voice network" /></ScenePosition>
  </ProductSceneStage>;
}

function SbcScene() {
return <ProductSceneStage name="sbc" label="Illustration of a Session Border Controller separating internal voice systems from external networks" wires={[{ from: "sbc-estate", to: "sbc-internal-estate", lit: true }, { from: "sbc-endpoints", to: "sbc-internal-endpoints", lit: true }, { from: "sbc-external-carriers", to: "sbc-carriers", lit: true }, { from: "sbc-external-cloud", to: "sbc-cloud", lit: true }, { from: "sbc-inspection", to: "sbc-inspector", lit: true }]}>
    <div aria-hidden className="absolute inset-y-[7%] left-1/2 border-l-2 border-dashed border-primary/20" />
    <ScenePosition x={55} y={40} w={250} joints={[{ id: "sbc-estate", side: "r", left: "100%", top: "65%" }]}><p className="mb-[1.5cqw] text-[1.7cqw] font-semibold">Inside your business</p><SceneWindow title="Voice estate"><SceneRow><Server className="size-[2cqw] text-primary" /><span>Office PBX</span></SceneRow><SceneRow><Headphones className="size-[2cqw] text-primary" /><span>Contact centre</span></SceneRow><SceneRow><Users className="size-[2cqw] text-primary" /><span>Cloud workspace</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={75} y={340} w={225} joints={[{ id: "sbc-endpoints", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Phone} title="SIP endpoints" detail="Internal registrations" /></ScenePosition>
    <ScenePosition x={410} y={135} w={200} joints={[{ id: "sbc-internal-estate", side: "l", left: "0%", top: "42%" }, { id: "sbc-internal-endpoints", side: "l", left: "0%", top: "65%" }, { id: "sbc-external-carriers", side: "r", left: "100%", top: "42%" }, { id: "sbc-external-cloud", side: "r", left: "100%", top: "65%" }, { id: "sbc-inspection", side: "b", left: "50%", top: "100%" }]}><Card className="gap-0 rounded-[3cqw] border-primary/25 bg-accent py-[3cqw] text-center shadow-xl shadow-primary/15"><CardContent className="px-[1cqw]"><ShieldCheck className="mx-auto size-[8cqw] text-primary" /><p className="mt-[1.7cqw] text-[1.8cqw] font-semibold">SBC</p><p className="mt-[0.5cqw] text-[1cqw] text-muted-foreground">Your controlled edge</p><div className="mt-[1.5cqw]"><SceneStatus>Policy boundary</SceneStatus></div></CardContent></Card></ScenePosition>
    <ScenePosition x={715} y={40} w={250} joints={[{ id: "sbc-carriers", side: "l", left: "0%", top: "70%" }]}><p className="mb-[1.5cqw] text-[1.7cqw] font-semibold">Beyond your network</p><SceneTile icon={Globe} title="Voice carriers" detail="External SIP connections" /></ScenePosition>
    <ScenePosition x={715} y={315} w={250} joints={[{ id: "sbc-cloud", side: "l", left: "0%", top: "50%" }]}><SceneTile icon={Network} title="Cloud platforms" detail="Interoperable voice paths" /></ScenePosition>
    <ScenePosition x={255} y={440} w={550} joints={[{ id: "sbc-inspector", side: "t", left: "46%", top: "0%" }]}><SceneWindow title="Session inspector"><div className="grid grid-cols-3 divide-x divide-border p-[1.6cqw]">{[{icon:Lock,title:"Access",detail:"IP policy"},{icon:ShieldCheck,title:"Protection",detail:"Signalling + media"},{icon:Network,title:"Routing",detail:"Internal ↔ external"}].map(({icon:Icon,title,detail}) => <div key={title} className="px-[1.5cqw]"><Icon className="mb-[0.7cqw] size-[1.8cqw] text-primary" /><p className="font-semibold">{title}</p><p className="mt-[0.3cqw] text-[0.9cqw] text-muted-foreground">{detail}</p></div>)}</div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function CrmScene() {
return <ProductSceneStage name="crm-integration" label="Illustration of a CRM contact record with caller context, a call sidebar and customer activity history" wires={[{ from: "crm-incoming", to: "crm-screen-pop", lit: true }, { from: "crm-context", to: "crm-call", lit: true }, { from: "crm-activity", to: "crm-record-log", lit: true }]}>
    <ScenePosition x={210} y={55} w={560} joints={[{ id: "crm-screen-pop", side: "l", left: "0%", top: "35%" }, { id: "crm-context", side: "r", left: "100%", top: "35%" }, { id: "crm-record-log", side: "r", left: "100%", top: "85%" }]}><SceneWindow title="Customer workspace / contact record"><div className="flex items-center justify-between border-b border-border px-[2cqw] py-[1cqw]"><span className="font-semibold">Contacts / Sarah Johnson</span><SceneStatus>Contact matched</SceneStatus></div><div className="grid grid-cols-[1.2fr_2fr]"><div className="space-y-[2cqw] border-r border-border bg-muted/20 p-[2cqw]"><ScenePerson detail="Northstar Office" /><div className="space-y-[1.2cqw] text-[1cqw]"><p><span className="block text-muted-foreground">Account</span>Office services</p><p><span className="block text-muted-foreground">Owner</span>Customer success</p><p><span className="block text-muted-foreground">Preferred channel</span>Business phone</p></div><span className="flex items-center justify-center gap-[0.6cqw] rounded-[0.7cqw] bg-primary p-[0.8cqw] text-[1cqw] text-primary-foreground"><PhoneCall className="size-[1.2cqw]" />Call contact</span></div><div className="p-[2cqw]"><p className="text-[1.6cqw] font-semibold">Customer activity</p><p className="mt-[0.5cqw] text-[1cqw] text-muted-foreground">A shared history, not another window.</p><div className="ml-[0.5cqw] mt-[2cqw] space-y-[2cqw] border-l border-primary/25 pl-[1.7cqw]">{[{title:"Inbound call",body:"Caller record surfaced for the team",icon:PhoneCall},{title:"Conversation notes",body:"Context kept against the contact",icon:FileText},{title:"Follow-up",body:"Next action visible to the account owner",icon:ArrowRight}].map(({title,body,icon:Icon}) => <div key={title} className="relative"><span className="absolute -left-[2.6cqw] flex size-[1.8cqw] items-center justify-center rounded-full bg-accent text-primary"><Icon className="size-[1cqw]" /></span><p className="font-medium">{title}</p><p className="mt-[0.4cqw] text-[1cqw] text-muted-foreground">{body}</p></div>)}</div></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={805} y={95} w={185} joints={[{ id: "crm-call", side: "l", left: "0%", top: "35%" }]}><SceneWindow title="SipLink call"><div className="space-y-[1.5cqw] p-[1.5cqw]"><ScenePerson name="Sarah Johnson" detail="Contact recognised" /><SceneWave animated /><SceneCallControls /><p className="border-t border-border pt-[1cqw] text-center text-[0.9cqw] text-muted-foreground">Context beside the call</p></div></SceneWindow></ScenePosition>
    <ScenePosition x={25} y={160} w={155} joints={[{ id: "crm-incoming", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={PhoneCall} title="Incoming" detail="Screen pop" /></ScenePosition>
    <ScenePosition x={785} y={480} w={205} joints={[{ id: "crm-activity", side: "l", left: "0%", top: "50%" }]}><SceneTile icon={FileText} title="Call activity" detail="Logged to the record" /></ScenePosition>
    <ScenePosition x={250} y={550} w={450}><div className="flex items-center justify-center gap-[1cqw] rounded-full border border-primary/15 bg-background px-[2cqw] py-[0.8cqw] text-[1cqw] shadow-lg shadow-primary/5"><Users className="size-[1.5cqw] text-primary" /><span>Customer information + communication</span><Check className="size-[1.2cqw] text-primary" /></div></ScenePosition>
  </ProductSceneStage>;
}

export function PlatformProductScene({ slug }: { slug: string }) {
  switch (slug) {
    case "voice-api": return <VoiceApiScene />;
    case "sms-api": return <SmsApiScene />;
    case "whatsapp-api": return <WhatsappScene />;
    case "webrtc-sdk": return <WebrtcScene />;
    case "sip-api": return <SipApiScene />;
    case "teams-calling": return <TeamsScene />;
    case "sbc": return <SbcScene />;
    case "crm-integration": return <CrmScene />;
    default: return null;
  }
}
