import { Activity, ArrowRight, AudioLines, Bot, CalendarDays, Check, Clock, FileAudio, GitBranch, Headset, ListOrdered, LockKeyhole, MessageSquare, Mic, Phone, Play, Search, ShieldCheck, SkipForward, SlidersHorizontal, Users, Volume2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ProductSceneStage, SceneCallControls, SceneLaptop, ScenePerson, ScenePhone, ScenePosition, SceneRow, SceneStatus, SceneTile, SceneWave, SceneWindow } from "@/components/site/product-scene-primitives";

const small = "size-[1.5cqw]";

function CallCenterScene() {
  return <ProductSceneStage name="call-center" label="Illustrative contact centre agent desktop linked to a supervisor console and incoming queue" wires={[{ from: "contact-queue", to: "agent-inbound", lit: true }, { from: "supervisor-monitor", to: "agent-monitor", lit: true }, { from: "agent-routing", to: "skills-routing", lit: true }]}>
    <ScenePosition x={35} y={100} w={220} joints={[{ id: "contact-queue", side: "r", left: "100%", top: "35%" }]}><SceneWindow title="Incoming · Support"><SceneRow active><Phone className={small} /><span>Account enquiry</span><Badge size="scene" className="text-[0.8cqw]">Next</Badge></SceneRow><SceneRow><Clock className={small} /><span>Delivery update</span><span>Waiting</span></SceneRow><SceneRow><Clock className={small} /><span>Billing question</span><span>Waiting</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={285} y={60} w={650} joints={[{ id: "agent-inbound", side: "l", left: "0%", top: "20%" }, { id: "agent-monitor", side: "l", left: "0%", top: "80%" }, { id: "agent-routing", side: "b", left: "75%", top: "100%" }]}><SceneLaptop title="Agent workspace"><div className="grid grid-cols-[1fr_2fr_1fr]"><div className="border-r border-border bg-muted/30 py-[2cqw]"><SceneRow active><Headset className={small} />Calls</SceneRow><SceneRow><Users className={small} />Team</SceneRow><SceneRow><FileAudio className={small} />History</SceneRow><SceneRow><MessageSquare className={small} />Notes</SceneRow></div><div className="space-y-[2cqw] p-[2.3cqw]"><SceneStatus>Inbound · Support</SceneStatus><ScenePerson detail="Account enquiry" /><SceneWave animated /><SceneCallControls /><div className="rounded-[0.7cqw] bg-muted p-[1cqw] text-[1cqw] text-muted-foreground">Call notes<br /><span className="text-foreground">Customer requested an account update.</span></div></div><div className="border-l border-border py-[1.5cqw]"><p className="px-[1cqw] font-semibold">Your team</p>{[["Daniel", "Available"], ["Elena", "On a call"], ["Marcus", "Available"]].map(([name,status]) => <SceneRow key={name}><span className="flex items-center gap-[0.5cqw]"><span className="size-[0.6cqw] rounded-full bg-primary/60" />{name}</span><span className="text-[0.8cqw] text-muted-foreground">{status}</span></SceneRow>)}</div></div></SceneLaptop></ScenePosition>
    <ScenePosition x={35} y={330} w={220} joints={[{ id: "supervisor-monitor", side: "r", left: "100%", top: "55%" }]}><SceneWindow title="Supervisor view"><div className="grid grid-cols-3 gap-[1cqw] p-[1.5cqw] text-center">{[["6","Agents"],["2","Waiting"],["4","Talking"]].map(([value,label]) => <div key={label}><p className="text-[2.4cqw] font-semibold text-primary">{value}</p><p className="text-[1cqw] text-muted-foreground">{label}</p></div>)}</div><SceneRow><Activity className={small} /><span>Support queue</span><SceneStatus>Monitored</SceneStatus></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={560} y={525} w={340} joints={[{ id: "skills-routing", side: "t", left: "65%", top: "0%" }]}><SceneTile icon={GitBranch} title="Skills routing" detail="The right call to the right agent" /></ScenePosition>
  </ProductSceneStage>;
}

function PredictiveScene() {
  return <ProductSceneStage name="predictive-dialer" label="Illustrative predictive dialler showing campaign call attempts passing through adaptive pacing to available agents" wires={[{ from: "campaign-answered", to: "pacing-answered", lit: true }, { from: "campaign-ringing", to: "pacing-ringing", lit: true }, { from: "attempt-outcomes", to: "pacing-outcomes", lit: true }, { from: "pacing-connected", to: "connected-agent", lit: true }, { from: "pacing-ready", to: "available-agent", lit: true }, { from: "pacing-control", to: "campaign-control", lit: true }]}>
    <ScenePosition x={25} y={25} w={280} joints={[{ id: "campaign-answered", side: "r", left: "100%", top: "55%" }, { id: "campaign-ringing", side: "r", left: "100%", top: "73%" }]}><SceneWindow title="Campaign · Follow-ups"><div className="p-[1.5cqw]"><p className="font-semibold">Today’s contact list</p><p className="text-[1cqw] text-muted-foreground">Dial only when the team is ready</p></div><SceneRow active><Phone className={small} /><span>Contact 018</span><span>Answered</span></SceneRow><SceneRow><Phone className={small} /><span>Contact 019</span><span>Ringing</span></SceneRow><SceneRow><Clock className={small} /><span>Contact 020</span><span>Scheduled</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={50} y={370} w={235} joints={[{ id: "attempt-outcomes", side: "r", left: "100%", top: "35%" }]}><SceneWindow title="Attempt outcomes"><SceneRow><Check className={small} /><span>Connected</span></SceneRow><SceneRow><Phone className={small} /><span>No answer</span></SceneRow><SceneRow><Clock className={small} /><span>Follow-up requested</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={365} y={175} w={285} joints={[{ id: "pacing-answered", side: "l", left: "0%", top: "22%" }, { id: "pacing-ringing", side: "l", left: "0%", top: "42%" }, { id: "pacing-outcomes", side: "l", left: "0%", top: "75%" }, { id: "pacing-connected", side: "r", left: "100%", top: "22%" }, { id: "pacing-ready", side: "r", left: "100%", top: "55%" }, { id: "pacing-control", side: "r", left: "100%", top: "85%" }]}><Card className="gap-0 border-primary/30 bg-accent/80 py-[2cqw] shadow-xl shadow-primary/10"><CardContent className="space-y-[1.5cqw] px-[2cqw] text-center"><SlidersHorizontal className="mx-auto size-[4cqw] text-primary" /><p className="text-[1.8cqw] font-semibold">Adaptive pacing</p><SceneWave animated /><div className="flex justify-between border-t border-primary/20 pt-[1cqw]"><span>Agent availability</span><span className="font-semibold text-primary">Ready</span></div><div className="flex justify-between"><span>Dialling pace</span><span>Balanced</span></div><SceneStatus>Connect human answers</SceneStatus></CardContent></Card></ScenePosition>
    <ScenePosition x={760} y={35} w={210} joints={[{ id: "connected-agent", side: "l", left: "0%", top: "35%" }]}><SceneWindow title="Agent · Sarah"><div className="space-y-[1.5cqw] p-[1.5cqw]"><ScenePerson name="Sarah Johnson" detail="Connected" /><SceneWave animated /><SceneCallControls /></div></SceneWindow></ScenePosition>
    <ScenePosition x={760} y={350} w={210} joints={[{ id: "available-agent", side: "l", left: "0%", top: "50%" }]}><SceneTile icon={Headset} title="Elena Ruiz" detail="Available for the next call" /></ScenePosition>
<ScenePosition x={740} y={445} w={240} joints={[{ id: "campaign-control", side: "l", left: "0%", top: "35%" }]}><SceneWindow title="Campaign control"><SceneRow><Headset className={small} /><span>Supervisor monitoring</span></SceneRow><SceneRow><FileAudio className={small} /><span>Call recording</span></SceneRow><SceneRow><ListOrdered className={small} /><span>Outcome logging</span></SceneRow></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function AutoScene() {
  return <ProductSceneStage name="auto-dialer" label="Illustrative auto dialler campaign board, contact list and active handset with recorded campaign outcomes" wires={[{ from: "campaign-call", to: "campaign-handset", lit: true }, { from: "campaign-results", to: "record-outcome", lit: true }]}>
    <ScenePosition x={35} y={70} w={690} joints={[{ id: "campaign-call", side: "r", left: "100%", top: "49%" }, { id: "campaign-results", side: "b", left: "85%", top: "100%" }]}><SceneWindow title="Campaign manager"><div className="flex items-center justify-between border-b border-border p-[1.8cqw]"><div><p className="text-[1.7cqw] font-semibold">Service follow-up</p><p className="text-[1cqw] text-muted-foreground">Contact list · Weekday campaign</p></div><SceneStatus>Running</SceneStatus></div><div className="grid grid-cols-[1fr_2fr]"><div className="border-r border-border bg-muted/25 p-[1.5cqw]"><p className="font-semibold">Campaign settings</p>{["Imported contacts", "Weekday calling hours", "Agent-led dialling", "Retry unanswered calls"].map(text => <p key={text} className="mt-[1.5cqw] flex items-center gap-[0.7cqw] text-[1cqw]"><Check className="size-[1cqw] text-primary" />{text}</p>)}<div className="mt-[2cqw] rounded-[0.8cqw] bg-accent p-[1cqw] text-[1cqw]">Next action<br /><span className="font-semibold">Continue contact list</span></div></div><div><SceneRow><span className="font-semibold">Contact</span><span className="font-semibold">Outcome</span></SceneRow>{[["Sarah Johnson","Calling"],["Daniel Ortiz","Completed"],["Elena Ruiz","Retry scheduled"],["Marcus Lee","Next in list"]].map(([name,status],i)=><SceneRow key={name} active={i===0}><span className="flex gap-[0.6cqw]"><Phone className={small}/>{name}</span><Badge size="scene" variant={i===0?"default":"secondary"} className="text-[0.8cqw]">{status}</Badge></SceneRow>)}<div className="flex items-center gap-[1cqw] p-[1.5cqw] text-[1cqw] text-muted-foreground"><span className="h-[0.5cqw] flex-1 rounded bg-muted"><span className="block h-full w-2/5 rounded bg-primary" /></span>List progress</div></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={790} y={25} w={185} joints={[{ id: "campaign-handset", side: "l", left: "0%", top: "60%" }]}><ScenePhone title="Campaign call"><div className="space-y-[1.7cqw] p-[1.5cqw]"><ScenePerson detail="Service follow-up" /><SceneWave animated /><SceneCallControls /><div className="rounded-[0.8cqw] bg-accent p-[1cqw] text-[1cqw]">Call script<br /><span className="text-muted-foreground">Check if the customer needs more help.</span></div></div></ScenePhone></ScenePosition>
    <ScenePosition x={120} y={485} w={570} joints={[{ id: "record-outcome", side: "t", left: "80%", top: "0%" }]}><SceneWindow title="Record the outcome"><div className="flex items-center justify-between p-[1.5cqw]">{["Completed","Call back","No answer"].map(text=><Badge size="scene" key={text} variant="secondary" className="px-[1cqw] text-[1cqw]">{text}</Badge>)}<SkipForward className="size-[2cqw] text-primary" /></div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function IvrScene() {
  return <ProductSceneStage name="ivr" label="Illustrative interactive voice response call-flow editor with greeting, menu choices, department routes and after-hours voicemail" wires={[{ from: "ivr-greeting-menu", to: "ivr-menu", lit: true }, { from: "ivr-greeting-hours", to: "ivr-after-hours", lit: true }, { from: "ivr-sales-route", to: "ivr-sales", lit: true }, { from: "ivr-support-route", to: "ivr-support", lit: true }, { from: "ivr-accounts-route", to: "ivr-accounts", lit: true }]}>
    <ScenePosition x={305} y={30} w={350} joints={[{ id: "ivr-greeting-menu", side: "b", left: "50%", top: "100%" }, { id: "ivr-greeting-hours", side: "r", left: "100%", top: "55%" }]}><SceneWindow title="Greeting · Main line"><div className="flex items-center gap-[1.5cqw] p-[1.5cqw]"><span className="flex size-[4cqw] items-center justify-center rounded-full bg-primary text-primary-foreground"><Play className="size-[2cqw]" /></span><div><p className="font-semibold">Welcome to SipLink</p><p className="text-[1cqw] text-muted-foreground">“How can we help you today?”</p><SceneWave animated className="h-[2cqw] justify-start" /></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={315} y={220} w={330} joints={[{ id: "ivr-menu", side: "t", left: "50%", top: "0%" }, { id: "ivr-sales-route", side: "b", left: "15%", top: "100%" }, { id: "ivr-accounts-route", side: "b", left: "50%", top: "100%" }, { id: "ivr-support-route", side: "b", left: "85%", top: "100%" }]}><SceneWindow title="Menu · Choose a department"><div className="bg-accent/30">{[["1","Sales enquiries"],["2","Customer support"],["3","Accounts and billing"]].map(([key,title])=><SceneRow key={key}><Badge size="scene" className="size-[2.4cqw] justify-center rounded-[0.6cqw] p-0 text-[1.2cqw]">{key}</Badge><span>{title}</span><ArrowRight className={small}/></SceneRow>)}</div></SceneWindow></ScenePosition>
    <ScenePosition x={45} y={460} w={280} joints={[{ id: "ivr-sales", side: "t", left: "50%", top: "0%" }]}><SceneWindow title="Sales team"><SceneRow><Users className={small}/><span>Ring available agents</span></SceneRow><SceneRow><Clock className={small}/><span>Weekday business hours</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={650} y={460} w={285} joints={[{ id: "ivr-support", side: "t", left: "50%", top: "0%" }]}><SceneWindow title="Support queue"><SceneRow><Headset className={small}/><span>Skills-based routing</span></SceneRow><SceneRow><Volume2 className={small}/><span>Queue announcement</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={395} y={460} w={185} joints={[{ id: "ivr-accounts", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Phone} title="Accounts" detail="Connect to extension" /></ScenePosition>
    <ScenePosition x={720} y={125} w={250} joints={[{ id: "ivr-after-hours", side: "l", left: "0%", top: "20%" }]}><SceneWindow title="Outside office hours"><div className="space-y-[1cqw] p-[1.5cqw]"><CalendarDays className="size-[2.5cqw] text-primary"/><p className="font-semibold">Leave a message</p><p className="text-[1cqw] text-muted-foreground">A different greeting when the team is away.</p><SceneStatus>Voicemail route</SceneStatus></div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function RecordingScene() {
  return <ProductSceneStage name="call-recording" label="Illustrative call recording workstation with audio timeline, recording library, conversation notes and controlled access" wires={[{ from: "recording-capture", to: "capture-source", lit: true }, { from: "recording-library", to: "recording-search", lit: true }, { from: "recording-policy", to: "recording-access", lit: true }]}>
    <ScenePosition x={50} y={30} w={755} joints={[{ id: "recording-capture", side: "r", left: "100%", top: "25%" }, { id: "recording-library", side: "b", left: "15%", top: "100%" }, { id: "recording-policy", side: "b", left: "85%", top: "100%" }]}><SceneWindow title="Recording workspace"><div className="grid grid-cols-[1fr_2fr]"><div className="border-r border-border bg-muted/20"><div className="flex items-center gap-[0.6cqw] p-[1.5cqw] font-semibold"><Search className={small}/>Recording library</div>{[["Customer support","Today · 10:42"],["Sales enquiry","Today · 09:15"],["Account update","Yesterday · 14:30"]].map(([title,time],i)=><SceneRow key={title} active={i===0}><FileAudio className={small}/><div className="flex-1"><p>{title}</p><p className="text-[0.85cqw] text-muted-foreground">{time}</p></div></SceneRow>)}</div><div className="space-y-[2cqw] p-[2cqw]"><div className="flex justify-between"><div><p className="text-[1.6cqw] font-semibold">Customer support</p><p className="text-[1cqw] text-muted-foreground">Sarah Johnson · Inbound</p></div><SceneStatus>Recorded</SceneStatus></div><div className="relative rounded-[0.9cqw] border border-border bg-accent/40 px-[1cqw] py-[2cqw]"><SceneWave className="h-[7cqw] gap-[0.75cqw] [&>span]:w-[0.65cqw]"/><div className="absolute inset-y-0 left-2/5 w-px bg-foreground/50"/><div className="mt-[1cqw] flex justify-between text-[0.85cqw] text-muted-foreground"><span>00:00</span><span>01:30</span><span>03:00</span></div></div><div className="flex items-center justify-between"><span className="flex items-center gap-[1cqw]"><Play className="size-[2.3cqw] text-primary"/>01:12 / 03:00</span><span className="text-[1cqw] text-muted-foreground">Playback · 1×</span><Volume2 className="size-[2cqw]"/></div><div className="border-t border-border pt-[1cqw]"><p className="font-semibold">Review note</p><p className="text-[1cqw] text-muted-foreground">Account enquiry resolved. Follow-up requested.</p></div></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={610} y={445} w={340} joints={[{ id: "recording-access", side: "t", left: "35%", top: "0%" }]}><SceneWindow title="Access and retention"><SceneRow><LockKeyhole className={small}/><span>Authorised reviewers</span><SceneStatus>Restricted</SceneStatus></SceneRow><SceneRow><ShieldCheck className={small}/><span>Recording policy</span><span>Applied</span></SceneRow><SceneRow><CalendarDays className={small}/><span>Retention rules</span><span>Configured</span></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={40} y={495} w={290} joints={[{ id: "recording-search", side: "t", left: "40%", top: "0%" }]}><SceneTile icon={FileAudio} title="Find the conversation" detail="Search by time, number or agent"/></ScenePosition>
    <ScenePosition x={845} y={90} w={115} joints={[{ id: "capture-source", side: "l", left: "0%", top: "50%" }]}><Card className="gap-0 border-primary/20 bg-accent py-[2cqw]"><CardContent className="px-[1cqw] text-center"><Mic className="mx-auto mb-[1cqw] size-[3cqw] text-primary"/><p className="font-semibold">Capture</p><p className="text-[0.9cqw] text-muted-foreground">Inbound<br/>Outbound</p></CardContent></Card></ScenePosition>
  </ProductSceneStage>;
}

function AnalyticsScene() {
  return <ProductSceneStage name="call-analytics" label="Illustrative call analytics dashboard with hourly call volume, outcomes, queue comparison and agent activity" wires={[{ from: "analytics-summary", to: "analytics-dashboard", lit: true }, { from: "analytics-team-route", to: "analytics-team", lit: true }, { from: "analytics-report-route", to: "analytics-reports", lit: true }]}>
    <ScenePosition x={200} y={35} w={765} joints={[{ id: "analytics-dashboard", side: "l", left: "0%", top: "40%" }, { id: "analytics-team-route", side: "b", left: "15%", top: "100%" }, { id: "analytics-report-route", side: "b", left: "85%", top: "100%" }]}><SceneWindow title="Call analytics · Business overview"><div className="flex items-center justify-between border-b border-border p-[1.7cqw]"><p className="text-[1.8cqw] font-semibold">Understand the calling day</p><Badge size="scene" variant="outline" className="text-[0.9cqw]">Today · All teams</Badge></div><div className="grid grid-cols-[2fr_1fr]"><div className="border-r border-border p-[2cqw]"><div className="flex justify-between"><p className="font-semibold">Call volume by hour</p><Activity className={small}/></div><div className="mt-[2cqw] flex h-[14cqw] items-end gap-[1cqw] border-b border-border">{[35,55,42,76,90,63,80,58,44,30].map((height,i)=><div key={i} className="flex-1 rounded-t-[0.4cqw] bg-primary/70" style={{height:`${height}%`}}/>)}</div><div className="mt-[0.7cqw] flex justify-between text-[0.85cqw] text-muted-foreground"><span>09:00</span><span>12:00</span><span>17:00</span></div></div><div className="p-[1.7cqw]"><p className="font-semibold">Call outcomes</p><div className="relative mx-auto my-[2cqw] flex size-[10cqw] items-center justify-center rounded-full border-[2cqw] border-primary/15 border-t-primary border-r-primary"><span className="text-[1cqw] font-semibold">Answered</span></div><p className="flex justify-between text-[1cqw]"><span>Answered</span><span>72</span></p><p className="mt-[0.5cqw] flex justify-between text-[1cqw] text-muted-foreground"><span>Missed</span><span>8</span></p><p className="mt-[0.5cqw] flex justify-between text-[1cqw] text-muted-foreground"><span>Voicemail</span><span>6</span></p></div></div><SceneRow><span>Queue comparison</span><span className="text-muted-foreground">Support</span><span className="h-[0.7cqw] w-[16cqw] rounded-full bg-primary/40"/><span>Sales</span><span className="h-[0.7cqw] w-[10cqw] rounded-full bg-primary/70"/></SceneRow></SceneWindow></ScenePosition>
    <ScenePosition x={25} y={120} w={135} joints={[{ id: "analytics-summary", side: "r", left: "100%", top: "50%" }]}><Card className="gap-0 bg-primary py-[2cqw] text-primary-foreground"><CardContent className="space-y-[2.5cqw] px-[1.5cqw]">{[["86","Total calls"],["04:12","Talk time"],["00:38","Wait time"]].map(([value,label])=><div key={label}><p className="text-[2.3cqw] font-semibold">{value}</p><p className="text-[1cqw] text-primary-foreground/80">{label}</p></div>)}</CardContent></Card></ScenePosition>
    <ScenePosition x={40} y={490} w={420} joints={[{ id: "analytics-team", side: "t", left: "65%", top: "0%" }]}><SceneWindow title="Team activity"><div className="flex justify-between p-[1.5cqw]">{["Support","Sales","Accounts"].map((team,i)=><div key={team}><p className="font-semibold">{team}</p><div className="mt-[1cqw] flex gap-[0.3cqw]">{Array.from({length:7-i},(_,j)=><span key={j} className="size-[1.2cqw] rounded-[0.2cqw] bg-primary/40"/>)}</div></div>)}</div></SceneWindow></ScenePosition>
    <ScenePosition x={690} y={490} w={285} joints={[{ id: "analytics-reports", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={CalendarDays} title="Scheduled reports" detail="A useful view for your next review"/></ScenePosition>
  </ProductSceneStage>;
}

function QueueScene() {
return <ProductSceneStage name="call-queue" label="Illustrative ordered support queue showing caller positions, waiting announcement, next available agent and overflow route" wires={[{ from: "queue-next", to: "queue-strategy-in", lit: true }, { from: "queue-strategy-out", to: "queue-agent", lit: true }, { from: "queue-overflow", to: "queue-fallback", lit: true }]}>
    <ScenePosition x={45} y={45} w={330} joints={[{ id: "queue-next", side: "r", left: "100%", top: "36%" }, { id: "queue-overflow", side: "b", left: "48%", top: "100%" }]}><SceneWindow title="Support queue"><div className="p-[1.5cqw]"><div className="flex items-center justify-between"><p className="text-[1.8cqw] font-semibold">You’re in line</p><ListOrdered className="size-[2cqw] text-primary"/></div><p className="text-[1cqw] text-muted-foreground">Calls answered in queue order</p></div>{[["1","Sarah Johnson","Next to answer"],["2","Daniel Ortiz","Waiting"],["3","Elena Ruiz","Waiting"],["4","Marcus Lee","Waiting"]].map(([position,name,status],i)=><SceneRow key={name} active={i===0}><span className="flex size-[3cqw] items-center justify-center rounded-full border border-primary/20 bg-background font-semibold text-primary">{position}</span><div className="flex-1"><p className="font-semibold">{name}</p><p className="text-[0.95cqw] text-muted-foreground">{status}</p></div><Phone className={small}/></SceneRow>)}<div className="flex items-center gap-[1cqw] border-t border-border p-[1.5cqw]"><Volume2 className="size-[2cqw] text-primary"/><p className="text-[1cqw]">“Our team will be with you shortly.”</p></div></SceneWindow></ScenePosition>
    <ScenePosition x={745} y={35} w={220} joints={[{ id: "queue-agent", side: "l", left: "0%", top: "36%" }]}><ScenePhone title="Available agent"><div className="space-y-[2cqw] p-[1.7cqw]"><ScenePerson name="Alex Morgan" detail="Support · Incoming call"/><SceneWave animated/><SceneCallControls/><div className="rounded-[0.8cqw] bg-accent p-[1cqw]"><p className="font-semibold">Next caller</p><p className="text-[1cqw] text-muted-foreground">Sarah Johnson · Queue position 1</p></div></div></ScenePhone></ScenePosition>
    <ScenePosition x={440} y={180} w={225} joints={[{ id: "queue-strategy-in", side: "l", left: "0%", top: "50%" }, { id: "queue-strategy-out", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Headset} title="Ring strategy" detail="Next available"/></ScenePosition>
    <ScenePosition x={45} y={485} w={570} joints={[{ id: "queue-fallback", side: "t", left: "28%", top: "0%" }]}><SceneWindow title="If the queue gets busy"><SceneRow><ArrowRight className={small}/><span>Overflow to another team</span><SceneStatus>Configured</SceneStatus></SceneRow><SceneRow><Mic className={small}/><span>Leave a voicemail after hours</span></SceneRow></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function AiScene() {
return <ProductSceneStage name="ai-voice-assistant" label="Illustrative voice assistant conversation with live transcript, enquiry context and a contextual handoff to a human support agent" height={660} wires={[{ from: "ai-assistant", to: "ai-transcript", lit: true }, { from: "ai-transcript-context", to: "ai-summary", lit: true }, { from: "ai-summary-handoff", to: "ai-human", lit: true }, { from: "ai-control", to: "ai-assistant-control", lit: true }]}>
    <ScenePosition x={35} y={110} w={285} joints={[{ id: "ai-assistant", side: "r", left: "100%", top: "35%" }, { id: "ai-assistant-control", side: "b", left: "50%", top: "100%" }]}><SceneWindow title="Voice assistant"><div className="space-y-[2cqw] p-[2cqw] text-center"><div className="mx-auto flex size-[13cqw] items-center justify-center rounded-full border border-primary/20 bg-accent ring-[1.3cqw] ring-primary/5"><div className="flex size-[9cqw] items-center justify-center rounded-full bg-primary/15"><Bot className="size-[5cqw] text-primary"/></div></div><p className="text-[1.8cqw] font-semibold">Listening to your caller</p><SceneWave animated/><SceneStatus>Natural conversation</SceneStatus></div></SceneWindow></ScenePosition>
    <ScenePosition x={395} y={35} w={360} joints={[{ id: "ai-transcript", side: "l", left: "0%", top: "30%" }, { id: "ai-transcript-context", side: "b", left: "50%", top: "100%" }]}><SceneWindow title="Conversation transcript"><div className="space-y-[1.3cqw] p-[1.7cqw]"><p className="text-[0.9cqw] text-muted-foreground">Caller · Sarah Johnson</p><div className="ml-[4cqw] rounded-[1cqw] bg-muted p-[1.3cqw]">I’d like help with my account.</div><div className="mr-[4cqw] rounded-[1cqw] bg-accent p-[1.3cqw]"><span className="mb-[0.4cqw] block text-[0.85cqw] font-semibold text-primary">SipLink assistant</span>I can help connect you. What do you need to change?</div><div className="ml-[4cqw] rounded-[1cqw] bg-muted p-[1.3cqw]">My contact details.</div><div className="mr-[4cqw] rounded-[1cqw] bg-accent p-[1.3cqw]">I’ll share that with the accounts team.</div><div className="flex items-center gap-[0.7cqw] border-t border-border pt-[1cqw] text-[1cqw]"><AudioLines className={small}/><span className="text-muted-foreground">Context collected for the next step</span></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={395} y={490} w={360} joints={[{ id: "ai-summary", side: "t", left: "50%", top: "0%" }, { id: "ai-summary-handoff", side: "r", left: "100%", top: "50%" }]}><SceneWindow title="Handoff summary"><div className="space-y-[0.6cqw] p-[1.5cqw]"><p><span className="text-muted-foreground">Intent:</span> Update account details</p><p><span className="text-muted-foreground">Destination:</span> Accounts team</p><div className="flex items-center gap-[0.8cqw] pt-[1cqw]"><Check className="size-[1.5cqw] text-primary"/><span>Carry the context into the call</span></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={800} y={180} w={185} joints={[{ id: "ai-human", side: "b", left: "50%", top: "100%" }]}><SceneWindow title="Human support"><div className="space-y-[1cqw] p-[1.5cqw]"><ScenePerson name="Alex Morgan" detail="Accounts team"/><SceneStatus>Ready to help</SceneStatus><SceneCallControls/></div></SceneWindow></ScenePosition>
    <ScenePosition x={55} y={535} w={245} joints={[{ id: "ai-control", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={ShieldCheck} title="Humans in control" detail="Escalate when a person is needed"/></ScenePosition>
  </ProductSceneStage>;
}

export function CallingProductScene({ slug }: { slug: string }) {
  switch (slug) {
    case "call-center": return <CallCenterScene />;
    case "predictive-dialer": return <PredictiveScene />;
    case "auto-dialer": return <AutoScene />;
    case "ivr": return <IvrScene />;
    case "call-recording": return <RecordingScene />;
    case "call-analytics": return <AnalyticsScene />;
    case "call-queue": return <QueueScene />;
    case "ai-voice-assistant": return <AiScene />;
    default: return null;
  }
}
