import { ArrowRight, Building2, Check, ClipboardCheck, Cloud, FileText, Headphones, Home, Laptop, MapPin, Monitor, Network, Phone, PhoneCall, Radio, Router, Search, Server, ShieldCheck, Smartphone, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ProductSceneStage, SceneCallControls, SceneLaptop, ScenePerson, ScenePhone, ScenePosition, SceneRow, SceneStatus, SceneTile, SceneWave, SceneWindow } from "@/components/site/product-scene-primitives";

function CloudWorkspace() {
  return <ProductSceneStage name="cloud-pbx" label="Illustrative cloud phone workspace linking a laptop call, a mobile handset and remote colleagues" wires={[{ from: "cloud-desk", to: "cloud-laptop-desk", lit: true }, { from: "cloud-laptop-phone", to: "cloud-phone", lit: true }, { from: "cloud-laptop-home", to: "cloud-home", lit: true }, { from: "cloud-laptop-team", to: "cloud-team", lit: true }]}>
    <ScenePosition x={185} y={58} w={570} joints={[{ id: "cloud-laptop-desk", side: "l", left: "0%", top: "25%" }, { id: "cloud-laptop-phone", side: "r", left: "100%", top: "45%" }, { id: "cloud-laptop-home", side: "b", left: "30%", top: "100%" }, { id: "cloud-laptop-team", side: "b", left: "80%", top: "100%" }]}><SceneLaptop title="Find a person or extension"><div className="grid grid-cols-[18%_54%_28%] min-h-[29cqw]">
      <div className="space-y-[1.1cqw] border-r border-border p-[1.2cqw] text-[1cqw]"><p className="flex gap-[0.5cqw]"><Home className="size-[1.3cqw]" />Home</p><p className="rounded-md bg-accent px-[0.4cqw] py-[0.7cqw] text-primary">Calls</p><p>Team</p><p>Voicemail</p><p>History</p></div>
      <div className="flex flex-col items-center justify-center gap-[1.5cqw] bg-primary/5 py-[2cqw]"><SceneStatus>Business voice</SceneStatus><ScenePerson detail="Customer call · ext. 204" /><SceneWave animated /><SceneCallControls /></div>
      <div className="p-[1.1cqw]"><p className="mb-[1.4cqw] font-semibold">Your team</p>{["Reception", "Sales", "Operations", "Support"].map((name,i) => <div key={name} className="mb-[1.4cqw] flex items-center gap-[0.6cqw]"><span className="flex size-[2.5cqw] items-center justify-center rounded-full bg-accent text-[0.8cqw] text-primary">{name[0]}</span><span className="text-[0.85cqw]">{name}<small className="block text-muted-foreground">{i === 1 ? "On a call" : "Available"}</small></span></div>)}</div>
    </div></SceneLaptop></ScenePosition>
    <ScenePosition x={800} y={154} w={168} joints={[{ id: "cloud-phone", side: "l", left: "0%", top: "30%" }]}><ScenePhone title="Your business line"><div className="space-y-[1.7cqw] px-[1cqw] py-[2cqw]"><ScenePerson name="Sarah Johnson" detail="Continue on mobile" /><SceneWave animated /><SceneCallControls /><p className="text-center text-[0.9cqw] text-muted-foreground">One extension. Any device.</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={20} y={38} w={145} joints={[{ id: "cloud-desk", side: "r", left: "100%", top: "60%" }]}><SceneTile icon={Monitor} title="Desk" detail="Office workspace" /></ScenePosition>
    <ScenePosition x={75} y={448} w={265} joints={[{ id: "cloud-home", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Home} title="Working from home" detail="Same team directory" /></ScenePosition>
    <ScenePosition x={510} y={465} w={260} joints={[{ id: "cloud-team", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Users} title="A connected team" detail="Shared call handling" /></ScenePosition>
  </ProductSceneStage>;
}

function HostedControl() {
  return <ProductSceneStage name="hosted-pbx" label="Illustrative hosted PBX platform console with a managed server rack and branch phone systems" wires={[{ from: "hosted-rack", to: "hosted-console", lit: true }, { from: "hosted-main-out", to: "hosted-main", lit: true }, { from: "hosted-branch-out", to: "hosted-branch", lit: true }, { from: "hosted-remote-out", to: "hosted-remote", lit: true }]}>
    <ScenePosition x={50} y={68} w={245} joints={[{ id: "hosted-rack", side: "r", left: "100%", top: "45%" }]}><Card className="gap-0 rounded-[2cqw] bg-foreground p-[1.8cqw] text-background shadow-xl"><CardContent className="space-y-[1.4cqw] p-0"><div className="flex items-center gap-[1cqw]"><Server className="size-[2.6cqw] text-primary" /><p className="font-semibold">Hosted platform</p></div>{["Voice routing", "Extensions", "System services", "Configuration"].map(label => <div key={label} className="flex h-[4.6cqw] items-center justify-between rounded-[0.6cqw] border border-background/20 bg-background/5 px-[1cqw]"><span className="text-[1cqw]">{label}</span><span className="flex gap-[0.4cqw]"><i className="scene-pulse size-[0.4cqw] rounded-full bg-primary" /><i className="scene-pulse size-[0.4cqw] rounded-full bg-primary/40" /></span></div>)}<p className="text-[0.9cqw] text-background/70">Managed by SipLink</p></CardContent></Card></ScenePosition>
    <ScenePosition x={370} y={35} w={575} joints={[{ id: "hosted-console", side: "l", left: "0%", top: "50%" }, { id: "hosted-main-out", side: "b", left: "15%", top: "100%" }, { id: "hosted-branch-out", side: "b", left: "50%", top: "100%" }, { id: "hosted-remote-out", side: "b", left: "85%", top: "100%" }]}><SceneWindow title="Platform administration"><div className="grid grid-cols-[27%_73%] min-h-[30cqw]"><div className="space-y-[1.8cqw] border-r border-border bg-muted/40 p-[1.5cqw]"><p className="font-semibold text-primary">System overview</p><p>Extensions</p><p>Call routes</p><p>Business hours</p><p>Access policies</p></div><div className="p-[1.8cqw]"><div className="flex items-center justify-between"><p className="text-[1.8cqw] font-semibold">Your phone system</p><SceneStatus>Hosted</SceneStatus></div><div className="my-[1.6cqw] grid grid-cols-2 gap-[1cqw]"><Card className="gap-0 rounded-[1cqw] bg-primary/5 p-[1.2cqw]"><CardContent className="p-0"><Cloud className="mb-[0.6cqw] size-[2cqw] text-primary" /><p className="font-semibold">Platform care</p><p className="text-[0.9cqw] text-muted-foreground">Hosting & maintenance</p></CardContent></Card><Card className="gap-0 rounded-[1cqw] p-[1.2cqw]"><CardContent className="p-0"><Users className="mb-[0.6cqw] size-[2cqw] text-primary" /><p className="font-semibold">Your teams</p><p className="text-[0.9cqw] text-muted-foreground">Conversations & callers</p></CardContent></Card></div><p className="mb-[0.6cqw] font-medium">Branch routing</p>{["Main office", "Branch office", "Remote team"].map((name,i) => <SceneRow key={name}><span>{name}</span><span className="text-[0.9cqw] text-muted-foreground">Ext. {200+i*100}–{249+i*100}</span><Check className="size-[1.2cqw] text-primary" /></SceneRow>)}</div></div></SceneWindow></ScenePosition>
    <ScenePosition x={68} y={515} w={245} joints={[{ id: "hosted-main", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Building2} title="Main office" detail="Desk phones" /></ScenePosition><ScenePosition x={443} y={515} w={245} joints={[{ id: "hosted-branch", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Building2} title="Branch office" detail="Shared platform" /></ScenePosition><ScenePosition x={753} y={515} w={225} joints={[{ id: "hosted-remote", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Laptop} title="Remote team" detail="Softphones" /></ScenePosition>
  </ProductSceneStage>;
}

function OnPremises() {
  return <ProductSceneStage name="ip-pbx" label="Illustrative office network floorplan with an on-site IP PBX, local desk phones and an external voice connection" wires={[{ from: "ip-pbx-reception", to: "ip-reception", lit: true }, { from: "ip-pbx-sales", to: "ip-sales", lit: true }, { from: "ip-pbx-office", to: "ip-office", lit: true }, { from: "ip-pbx-softphone", to: "ip-softphone", lit: true }, { from: "ip-pbx-external", to: "ip-external", lit: true }]}>
    <ScenePosition x={38} y={15} w={925} className="-z-10"><Card className="h-[51cqw] gap-0 rounded-[3cqw] border-dashed bg-muted/20 p-[2cqw] shadow-none"><CardContent className="p-0"><div className="flex items-center justify-between"><p className="flex items-center gap-[0.8cqw] font-semibold"><Building2 className="size-[2cqw] text-primary" />Your premises</p><Badge size="scene" variant="outline" className="text-[1cqw]">Local network</Badge></div></CardContent></Card></ScenePosition>
    <ScenePosition x={95} y={84} w={240} joints={[{ id: "ip-reception", side: "r", left: "100%", top: "75%" }]}><SceneWindow title="Reception · 201"><div className="space-y-[0.8cqw] p-[1.5cqw]"><Phone className="size-[2.5cqw] text-primary" /><p className="text-[1.8cqw] font-semibold">Desk phone</p><SceneWave animated /><div className="grid grid-cols-3 gap-[0.4cqw]">{[1,2,3,4,5,6].map(n => <span key={n} className="rounded bg-muted py-[0.3cqw] text-center text-[0.8cqw]">{n}</span>)}</div></div></SceneWindow></ScenePosition>
    <ScenePosition x={670} y={85} w={255} joints={[{ id: "ip-sales", side: "l", left: "0%", top: "75%" }]}><SceneWindow title="Sales workspace"><div className="p-[1.5cqw]"><ScenePerson compact name="Sales team" detail="Internal extension 214" /><div className="mt-[1.2cqw] space-y-[0.5cqw]"><SceneRow active>Internal call <PhoneCall className="size-[1.4cqw]" /></SceneRow><SceneRow>Team directory <Users className="size-[1.4cqw]" /></SceneRow></div></div></SceneWindow></ScenePosition>
    <ScenePosition x={365} y={215} w={265} joints={[{ id: "ip-pbx-reception", side: "l", left: "0%", top: "30%" }, { id: "ip-pbx-sales", side: "r", left: "100%", top: "30%" }, { id: "ip-pbx-office", side: "l", left: "0%", top: "75%" }, { id: "ip-pbx-softphone", side: "r", left: "100%", top: "75%" }, { id: "ip-pbx-external", side: "b", left: "50%", top: "100%" }]}><Card className="gap-0 rounded-[1.8cqw] bg-foreground p-[1.8cqw] text-background shadow-xl"><CardContent className="p-0"><Server className="mb-[1cqw] size-[3cqw] text-primary" /><p className="text-[2cqw] font-semibold">Your IP PBX</p><p className="mt-[0.7cqw] text-[1cqw] text-background/70">Call control on site</p><div className="mt-[1.5cqw] flex gap-[0.7cqw]">{Array.from({length:8},(_,i) => <span key={i} className="scene-pulse h-[1.1cqw] w-[1.3cqw] rounded-sm border border-primary/50 bg-primary/15" />)}</div></CardContent></Card></ScenePosition>
    <ScenePosition x={88} y={431} w={255} joints={[{ id: "ip-office", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Router} title="Office network" detail="IP-enabled endpoints" /></ScenePosition><ScenePosition x={676} y={431} w={254} joints={[{ id: "ip-softphone", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Monitor} title="Softphone" detail="Internal extension 305" /></ScenePosition><ScenePosition x={358} y={535} w={280} joints={[{ id: "ip-external", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Network} title="External voice network" detail="SIP connectivity" /></ScenePosition>
  </ProductSceneStage>;
}

function DirectDirectory() {
  return <ProductSceneStage name="did-numbers" label="Illustrative direct-number directory routing separate numbers to people, teams and extensions" wires={[{ from: "did-reception-out", to: "did-reception", lit: true }, { from: "did-sales-out", to: "did-sales", lit: true }, { from: "did-support-out", to: "did-support", lit: true }, { from: "did-accounts-out", to: "did-accounts", lit: true }]}>
    <ScenePosition x={40} y={46} w={550} joints={[{ id: "did-reception-out", side: "r", left: "100%", top: "52.6%" }, { id: "did-sales-out", side: "r", left: "100%", top: "64.8%" }, { id: "did-support-out", side: "b", left: "22%", top: "100%" }, { id: "did-accounts-out", side: "b", left: "75%", top: "100%" }]}><SceneWindow title="Number directory"><div className="p-[2cqw]"><div className="flex items-center justify-between"><div><p className="text-[2.4cqw] font-semibold">Direct lines</p><p className="text-[1cqw] text-muted-foreground">A number for each destination</p></div><Phone className="size-[3cqw] text-primary" /></div><div className="my-[1.8cqw] flex items-center gap-[1cqw] rounded-[0.8cqw] bg-muted px-[1cqw] py-[0.9cqw] text-[1cqw] text-muted-foreground"><Search className="size-[1.3cqw]" />Search number or department</div><div className="grid grid-cols-[45%_35%_20%] border-b border-border pb-[0.8cqw] text-[0.85cqw] text-muted-foreground"><span>Business number</span><span>Destination</span><span>Extension</span></div>{[["+1 (212) 555-0101","Reception","201"],["+1 (212) 555-0102","Sales","214"],["+1 (212) 555-0103","Support","305"],["+1 (212) 555-0104","Accounts","410"]].map(([number,team,ext],i) => <div key={number} className={`grid grid-cols-[45%_35%_20%] items-center border-b border-border py-[1.8cqw] text-[1.1cqw] ${i === 1 ? "bg-primary/5" : ""}`}><span className="font-medium">{number}</span><span>{team}</span><span className="text-primary">{ext}</span></div>)}</div></SceneWindow></ScenePosition>
    <ScenePosition x={708} y={50} w={250} joints={[{ id: "did-reception", side: "l", left: "0%", top: "50%" }]}><SceneWindow title="Reception"><div className="p-[1.2cqw]"><ScenePerson compact name="Main desk" detail="Direct to extension 201" /><SceneWave animated /></div></SceneWindow></ScenePosition>
    <ScenePosition x={730} y={205} w={175} joints={[{ id: "did-sales", side: "l", left: "0%", top: "35%" }]}><ScenePhone title="Sales · 214"><div className="space-y-[1cqw] px-[1cqw] py-[1.4cqw]"><ScenePerson name="Sales team" detail="Direct incoming call · 214" /><SceneWave animated /><SceneCallControls /><p className="text-center text-[0.9cqw] text-muted-foreground">Your own direct business line</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={40} y={516} w={260} joints={[{ id: "did-support", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Headphones} title="Support team" detail="Direct to extension 305" /></ScenePosition><ScenePosition x={355} y={516} w={340} joints={[{ id: "did-accounts", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Users} title="Accounts team" detail="Direct to extension 410" /></ScenePosition>
  </ProductSceneStage>;
}

function TollFreeReception() {
  return <ProductSceneStage name="toll-free-numbers" label="Illustrative toll-free entry number connecting an inbound caller to a receptionist console and departmental teams" wires={[{ from: "toll-caller", to: "toll-reception", lit: true }, { from: "toll-sales-out", to: "toll-sales", lit: true }, { from: "toll-support-out", to: "toll-support", lit: true }, { from: "toll-accounts-out", to: "toll-accounts", lit: true }]}>
    <ScenePosition x={45} y={60} w={205} joints={[{ id: "toll-caller", side: "r", left: "100%", top: "45%" }]}><ScenePhone title="Calling your business"><div className="px-[1.8cqw] py-[2.2cqw] text-center"><PhoneCall className="mx-auto mb-[1.5cqw] size-[4cqw] text-primary" /><p className="text-[1cqw] text-muted-foreground">Toll-free entry number</p><p className="mt-[0.7cqw] text-[2cqw] font-semibold">1800 XXX XXXX</p><div className="my-[2.3cqw]"><SceneWave animated /></div><SceneCallControls /><p className="mt-[2cqw] text-[1cqw] text-muted-foreground">Customer conversation</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={368} y={66} w={590} joints={[{ id: "toll-reception", side: "l", left: "0%", top: "45%" }, { id: "toll-sales-out", side: "b", left: "10%", top: "100%" }, { id: "toll-support-out", side: "b", left: "53%", top: "100%" }, { id: "toll-accounts-out", side: "b", left: "90%", top: "100%" }]}><SceneLaptop title="Reception desk"><div className="grid grid-cols-[60%_40%] min-h-[30cqw]"><div className="p-[2cqw]"><SceneStatus>Incoming call</SceneStatus><div className="my-[2cqw]"><ScenePerson detail="From your toll-free number" /></div><SceneWave animated /><SceneCallControls /></div><div className="border-l border-border bg-muted/30 p-[1.5cqw]"><p className="mb-[1.5cqw] font-semibold">Where can we help?</p>{["Sales enquiries", "Customer support", "Accounts"].map((name,i) => <Card key={name} className="mb-[1cqw] gap-0 rounded-[0.8cqw] p-[1cqw]"><CardContent className="flex items-center justify-between p-0"><div><p className="text-[1cqw] font-medium">{name}</p><p className="text-[0.85cqw] text-muted-foreground">Team {i+1}</p></div><ArrowRight className="size-[1.3cqw] text-primary" /></CardContent></Card>)}<p className="mt-[1.5cqw] text-[0.9cqw] text-muted-foreground">Route by department or business hours</p></div></div></SceneLaptop></ScenePosition>
    <ScenePosition x={65} y={493} w={235}><SceneTile icon={Radio} title="One public number" detail="Across customer touchpoints" /></ScenePosition><ScenePosition x={331} y={529} w={200} joints={[{ id: "toll-sales", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Users} title="Sales" /></ScenePosition><ScenePosition x={577} y={529} w={210} joints={[{ id: "toll-support", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={Headphones} title="Support" /></ScenePosition><ScenePosition x={818} y={529} w={165} joints={[{ id: "toll-accounts", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={FileText} title="Accounts" /></ScenePosition>
  </ProductSceneStage>;
}

function VirtualPresence() {
  return <ProductSceneStage name="virtual-numbers" label="Illustrative geographic number presence map forwarding local business calls to a roaming team handset" wires={[{ from: "virtual-local", to: "virtual-routing-local", lit: true }, { from: "virtual-location", to: "virtual-routing-location", lit: true }, { from: "virtual-market", to: "virtual-routing-market", lit: true }, { from: "virtual-routing-phone", to: "virtual-phone", lit: true }, { from: "virtual-forwarding", to: "virtual-routing-config", lit: true }]}>
    <ScenePosition x={15} y={35} w={740} className="-z-10"><Card className="h-[50cqw] gap-0 overflow-hidden rounded-[3cqw] bg-muted/20 p-[2cqw] shadow-none"><CardContent className="p-0"><div className="flex items-center gap-[0.8cqw]"><MapPin className="size-[2cqw] text-primary" /><p className="font-semibold">A local presence. A flexible destination.</p></div><svg aria-hidden viewBox="0 0 740 500" className="absolute inset-0 size-full fill-primary/5 stroke-border" strokeWidth="1.5"><path d="M70 140L180 80 270 115 335 65 425 115 500 95 620 165 650 285 585 340 520 430 370 445 280 390 190 430 90 310Z"/><path d="M180 80L190 430M335 65L280 390M500 95L520 430M70 220L620 165M90 310L585 340"/><circle cx="180" cy="165" r="35" className="fill-primary/10 stroke-primary/20"/><circle cx="430" cy="100" r="30" className="fill-primary/10 stroke-primary/20"/><circle cx="310" cy="365" r="40" className="fill-primary/10 stroke-primary/20"/></svg></CardContent></Card></ScenePosition>
    <ScenePosition x={71} y={155} w={227} joints={[{ id: "virtual-local", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Building2} title="Local office" detail="Regional business number" /></ScenePosition><ScenePosition x={326} y={74} w={226} joints={[{ id: "virtual-location", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={MapPin} title="Another location" detail="A familiar local entry point" /></ScenePosition><ScenePosition x={203} y={376} w={230} joints={[{ id: "virtual-market", side: "r", left: "100%", top: "50%" }]}><SceneTile icon={Building2} title="New market" detail="Presence without a new desk" /></ScenePosition>
    <ScenePosition x={590} y={220} w={164} joints={[{ id: "virtual-routing-local", side: "l", left: "2%", top: "35%" }, { id: "virtual-routing-location", side: "t", left: "50%", top: "0%" }, { id: "virtual-routing-market", side: "l", left: "2%", top: "65%" }, { id: "virtual-routing-phone", side: "r", left: "100%", top: "50%" }, { id: "virtual-routing-config", side: "b", left: "50%", top: "100%" }]}><Card className="gap-0 rounded-full bg-primary p-[1.8cqw] text-center text-primary-foreground shadow-xl"><CardContent className="p-0"><Phone className="mx-auto mb-[0.6cqw] size-[3cqw]" /><p className="font-semibold">Call routing</p><p className="text-[0.9cqw]">Your chosen destination</p></CardContent></Card></ScenePosition>
    <ScenePosition x={798} y={80} w={175} joints={[{ id: "virtual-phone", side: "l", left: "0%", top: "50%" }]}><ScenePhone title="Your team, anywhere"><div className="space-y-[1.7cqw] px-[1cqw] py-[2cqw]"><ScenePerson name="Sarah Johnson" detail="Business number call" /><SceneWave animated /><SceneCallControls /><p className="text-center text-[0.9cqw] text-muted-foreground">The number stays.<br/>The destination moves.</p></div></ScenePhone></ScenePosition>
    <ScenePosition x={523} y={489} w={400} joints={[{ id: "virtual-forwarding", side: "t", left: "37%", top: "0%" }]}><SceneWindow title="Forwarding destination"><div className="flex items-center justify-between p-[1.5cqw]"><span className="flex items-center gap-[0.7cqw]"><Smartphone className="size-[2cqw] text-primary" />Team mobile</span><SceneStatus>Configured</SceneStatus></div></SceneWindow></ScenePosition>
  </ProductSceneStage>;
}

function PortingJourney() {
  return <ProductSceneStage name="number-porting" label="Illustrative number-transfer paperwork journey from an existing provider to SipLink with a continuity phone" wires={[{ from: "port-provider", to: "port-plan-in", lit: true }, { from: "port-plan-out", to: "port-siplink-in", lit: true }, { from: "port-plan-handover", to: "port-handover", lit: true }, { from: "port-plan-continuity", to: "port-continuity", lit: true }, { from: "port-siplink-phone", to: "port-phone", lit: true }]}>
    <ScenePosition x={20} y={90} w={218} joints={[{ id: "port-provider", side: "r", left: "100%", top: "50%" }]}><SceneWindow title="Existing provider"><div className="p-[1.8cqw]"><Building2 className="mb-[1cqw] size-[3cqw] text-muted-foreground" /><p className="font-semibold">Your current lines</p>{["555-0101","555-0102","555-0103"].map(number => <p key={number} className="mt-[1cqw] rounded bg-muted px-[0.8cqw] py-[0.6cqw] text-[1cqw]">{number}</p>)}</div></SceneWindow></ScenePosition>
    <ScenePosition x={302} y={36} w={400} joints={[{ id: "port-plan-in", side: "l", left: "0%", top: "50%" }, { id: "port-plan-out", side: "r", left: "100%", top: "45%" }, { id: "port-plan-handover", side: "b", left: "25%", top: "100%" }, { id: "port-plan-continuity", side: "b", left: "80%", top: "100%" }]}><Card className="gap-0 rounded-[1.2cqw] bg-card p-[2.3cqw] shadow-xl shadow-primary/10"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-border pb-[1.3cqw]"><FileText className="size-[3cqw] text-primary" /><Badge size="scene" variant="secondary" className="text-[0.9cqw]">Transfer plan</Badge></div><p className="mt-[1.5cqw] text-[2.2cqw] font-semibold">Keep your numbers</p><p className="mt-[0.7cqw] text-[1cqw] text-muted-foreground">Check eligibility before scheduling a move.</p><div className="mt-[2cqw] space-y-[1.4cqw]">{["Confirm number ownership", "Prepare authorisation details", "Agree the transfer schedule", "Validate incoming call routing"].map((step,i) => <div key={step} className="flex items-center gap-[1cqw]"><span className="flex size-[2.1cqw] shrink-0 items-center justify-center rounded-full bg-accent text-[0.9cqw] text-primary">{i+1}</span><span className="text-[1.1cqw]">{step}</span></div>)}</div><div className="mt-[2cqw] border-t border-border pt-[1.2cqw]"><p className="text-[0.9cqw] text-muted-foreground">Eligible numbers • Coordinated cutover</p></div></CardContent></Card></ScenePosition>
    <ScenePosition x={773} y={45} w={207} joints={[{ id: "port-siplink-in", side: "l", left: "0%", top: "55%" }, { id: "port-siplink-phone", side: "b", left: "41%", top: "100%" }]}><SceneWindow title="SipLink"><div className="p-[1.8cqw]"><Phone className="mb-[1cqw] size-[3cqw] text-primary" /><p className="font-semibold">Same business numbers</p>{["555-0101","555-0102","555-0103"].map(number => <div key={number} className="mt-[0.9cqw] flex items-center justify-between text-[1cqw]"><span>{number}</span><Check className="size-[1.2cqw] text-primary" /></div>)}</div></SceneWindow></ScenePosition>
    <ScenePosition x={780} y={285} w={155} joints={[{ id: "port-phone", side: "t", left: "50%", top: "0%" }]}><ScenePhone title="Same familiar number"><div className="space-y-[1cqw] px-[1cqw] py-[1.6cqw]"><ScenePerson name="Your customer" detail="No new number to learn" /><SceneWave animated /><SceneCallControls /></div></ScenePhone></ScenePosition>
    <ScenePosition x={55} y={500} w={370} joints={[{ id: "port-handover", side: "t", left: "70%", top: "0%" }]}><SceneTile icon={ClipboardCheck} title="A planned handover" detail="Ownership, timing and routing reviewed together" /></ScenePosition><ScenePosition x={470} y={500} w={250} joints={[{ id: "port-continuity", side: "t", left: "50%", top: "0%" }]}><SceneTile icon={ShieldCheck} title="Continuity first" detail="Your customer-facing identity" /></ScenePosition>
  </ProductSceneStage>;
}

export function VoiceProductScene({ slug }: { slug: string }) {
  switch (slug) {
    case "cloud-pbx": return <CloudWorkspace />;
    case "hosted-pbx": return <HostedControl />;
    case "ip-pbx": return <OnPremises />;
    case "did-numbers": return <DirectDirectory />;
    case "toll-free-numbers": return <TollFreeReception />;
    case "virtual-numbers": return <VirtualPresence />;
    case "number-porting": return <PortingJourney />;
    default: return null;
  }
}
